# Generated by Django 4.1.7 on 2023-03-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posiciones',
            name='calificacionc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='posiciones',
            name='calificacionj',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='posiciones',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
