# Generated by Django 4.1.7 on 2023-03-07 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_posiciones_calificacionc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to='app/static/image/')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posiciones', to='app.posiciones')),
            ],
        ),
    ]
