# Generated by Django 4.1.7 on 2023-03-07 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
